version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - ${DB_NAME}
networks:
  excelAlikeEditor:
